// <auto-generated />
using System;
using EmployeesApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeesApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200506202716_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeesApp.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerformanceManagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeesApp.API.Models.Employee", b =>
                {
                    b.HasOne("EmployeesApp.API.Models.Employee", "PerformanceManager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("PerformanceManagerId");
                });
#pragma warning restore 612, 618
        }
    }
}
